name: Compile LaTeX with XeLaTeX

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install SimSun font
        run: |
          apt-get update
          apt-get install -y fonts-arphic-uming
          fc-cache -f -v
          
      - name: Create output directory
        run: mkdir -p output

      - name: Compile LaTeX document
        run: |
          xelatex -interaction=nonstopmode -output-directory=output PlantUML_Language_Reference_Guide_en.tex
          xelatex -interaction=nonstopmode -output-directory=output PlantUML_Language_Reference_Guide_en.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PlantUML_Language_Reference_Guide_en-pdf
          path: output/PlantUML_Language_Reference_Guide_en.pdf
