name: Compile LaTeX with XeLaTeX

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        run: xelatex -interaction=nonstopmode -output-directory=output hello.tex
